apiVersion: v1
kind: Service
metadata:
  name: sports-content-gen-service
spec:
  type: LoadBalancer # AWS will provision an ELB if using EKS
  selector:
    app: sports-content-gen # Must match the deployment label exactly
  ports:
  - protocol: TCP
    port: 80        # The public internet port
    targetPort: 8501 # The internal app port